/**
 * feeCron.js — Late-fee auto-calculation + periodic fee-demand auto-generation
 *
 * Run via: node scripts/feeCron.js
 * Or schedule with PM2 / system cron:  0 1 * * * node /path/to/scripts/feeCron.js
 *
 * For each school with fees module enabled:
 *   1. Auto-generate recurring/quarterly/half-yearly fee demands for active structures
 *   2. Find all active fine rules
 *   3. Resolve each active student's fee items
 *   4. If any item is past due + grace period, create a DEBIT fine ledger entry
 *   5. Skip students who already have a fine entry for today
 */

require('dotenv').config();
const mongoose = require('mongoose');

const School               = require('../models/School');
const AcademicYear         = require('../models/AcademicYear');
const User                 = require('../models/User');
const StudentProfile       = require('../models/StudentProfile');
const FineRule             = require('../models/FineRule');
const FeeStructure         = require('../models/FeeStructure');
const FeeHead              = require('../models/FeeHead');
const StudentFeeAssignment = require('../models/StudentFeeAssignment');
const ClassSection         = require('../models/ClassSection');
const FeeLedger            = require('../models/FeeLedger');

const DB_URI = process.env.MONGODB_URI || process.env.MONGO_URI || 'mongodb://localhost:27017/school';

async function getStudentFeeItems(studentId, academicYearId, schoolId) {
    const sfa = await StudentFeeAssignment.findOne({
        school: schoolId, student: studentId, academicYear: academicYearId, isActive: true,
    }).populate({ path: 'feeStructure', populate: { path: 'items.feeHead' } });
    if (sfa && sfa.feeStructure) {
        return (sfa.feeStructure.items || []).filter(i => i.isActive);
    }

    const sp = await StudentProfile.findOne({ user: studentId, school: schoolId })
        .populate({ path: 'currentSection', populate: { path: 'class' } });
    if (!sp || !sp.currentSection) return [];

    const sectionStruct = await FeeStructure.findOne({
        school: schoolId, academicYear: academicYearId,
        level: 'section', section: sp.currentSection._id, isActive: true,
    });
    if (sectionStruct) return (sectionStruct.items || []).filter(i => i.isActive);

    const classId = sp.currentSection.class?._id || sp.currentSection.class;
    if (!classId) return [];
    const classStruct = await FeeStructure.findOne({
        school: schoolId, academicYear: academicYearId,
        level: 'class', class: classId, isActive: true,
    });
    return classStruct ? (classStruct.items || []).filter(i => i.isActive) : [];
}

const MONTH_NAMES = ['January','February','March','April','May','June',
                     'July','August','September','October','November','December'];

async function shouldChargeItem(schoolId, studentId, academicYearId, item, startDate) {
    const feeType = item.feeHead?.type || 'recurring';
    if (feeType === 'one_time') return null; // one_time never auto-charges; skip in cron

    const now = new Date();
    const sy = startDate.getFullYear(), sm = startDate.getMonth();
    const cy = now.getFullYear(),        cm = now.getMonth();
    const monthsElapsed = (cy - sy) * 12 + (cm - sm);

    let periodNum;
    if      (feeType === 'recurring')   periodNum = monthsElapsed;
    else if (feeType === 'quarterly')   periodNum = Math.floor(monthsElapsed / 3);
    else if (feeType === 'half_yearly') periodNum = Math.floor(monthsElapsed / 6);
    else return null;

    const hit = await FeeLedger.findOne({
        school: schoolId, student: studentId, academicYear: academicYearId,
        category: 'fee_charged', feeItemId: item._id, feePeriod: periodNum,
    });
    if (hit) return null;

    // Build period label
    let periodLabel;
    if (feeType === 'recurring') {
        periodLabel = `${MONTH_NAMES[cm]} ${cy}`;
    } else if (feeType === 'quarterly') {
        const chargeMonth = new Date(sy, sm + periodNum * 3, 1);
        periodLabel = `Quarter ${periodNum + 1} — ${MONTH_NAMES[chargeMonth.getMonth()]} ${chargeMonth.getFullYear()}`;
    } else {
        const chargeMonth = new Date(sy, sm + periodNum * 6, 1);
        periodLabel = `Half ${periodNum + 1} — ${MONTH_NAMES[chargeMonth.getMonth()]} ${chargeMonth.getFullYear()}`;
    }
    return { periodNum, periodLabel };
}

async function autoGenerateDemands(school, ay) {
    const structures = await FeeStructure.find({
        school: school._id, academicYear: ay._id, isActive: true, demandGenerated: true,
    }).populate('items.feeHead');

    let totalEntries = 0;
    for (const structure of structures) {
        const activeItems = (structure.items || []).filter(i => i.isActive && i.feeHead);
        // Only handle periodic types (not one_time — that was already charged on first demand)
        const periodicItems = activeItems.filter(i =>
            ['recurring', 'quarterly', 'half_yearly'].includes(i.feeHead.type)
        );
        if (!periodicItems.length) continue;

        let studentIds = [];
        if (structure.level === 'section' && structure.section) {
            const sec = await ClassSection.findById(structure.section).select('enrolledStudents');
            studentIds = sec?.enrolledStudents || [];
        } else if (structure.level === 'class' && structure.class) {
            const secs = await ClassSection.find({ school: school._id, class: structure.class, status: 'active' })
                .select('enrolledStudents');
            studentIds = secs.flatMap(s => s.enrolledStudents || []);
        }
        if (!studentIds.length) continue;

        if (!structure.demandStartedAt) continue; // skip if never manually generated

        for (const studentId of studentIds) {
            for (const item of periodicItems) {
                const result = await shouldChargeItem(
                    school._id, studentId, ay._id, item, structure.demandStartedAt
                );
                if (!result) continue;

                const prevBal = await FeeLedger.findOne(
                    { school: school._id, student: studentId, academicYear: ay._id },
                    { runningBalance: 1 }, { sort: { createdAt: -1 } }
                );
                const runningBalance = Math.round(((prevBal?.runningBalance || 0) + item.amount) * 100) / 100;

                await FeeLedger.create({
                    school: school._id, student: studentId, academicYear: ay._id,
                    entryType: 'debit', category: 'fee_charged', amount: item.amount,
                    description: `${item.feeHead.name} — ${result.periodLabel}`,
                    referenceType: 'FeeStructure', referenceId: structure._id,
                    feeItemId: item._id, feePeriod: result.periodNum,
                    periodLabel: result.periodLabel,
                    feeHeadName: item.feeHead.name || '',
                    runningBalance, createdBy: null,
                });
                totalEntries++;
            }
        }
    }
    console.log(`  [${school.name}] Auto-demand entries created: ${totalEntries}`);
}

function calcFine(items, rule, date = new Date()) {
    let total = 0;
    const details = [];
    for (const item of items) {
        if (!item.dueDate) continue;
        const graceDue = new Date(
            new Date(item.dueDate).getTime() + (rule.gracePeriodDays || 0) * 86400000
        );
        if (date <= graceDue) continue;
        const daysLate = Math.max(1, Math.floor((date - graceDue) / 86400000));
        let fine = rule.fineType === 'flat' ? rule.flatAmount : rule.perDayAmount * daysLate;
        if (rule.maxCap > 0) fine = Math.min(fine, rule.maxCap);
        total += fine;
        details.push({ feeName: item.feeHead?.name || 'Fee', daysLate, fine });
    }
    return { total: Math.round(total * 100) / 100, details };
}

async function runForSchool(school) {
    const ay = await AcademicYear.findOne({ school: school._id, status: 'active' });
    if (!ay) return;

    // Auto-generate periodic fee demands (recurring/quarterly/half-yearly)
    await autoGenerateDemands(school, ay);

    const fineRules = await FineRule.find({ school: school._id, isActive: true });
    if (!fineRules.length) return;

    const students = await User.find({ school: school._id, role: 'student', isActive: true }).select('_id');
    const today    = new Date();
    const todayKey = today.toISOString().split('T')[0]; // YYYY-MM-DD

    let fineCount = 0;
    for (const student of students) {
        const items = await getStudentFeeItems(student._id, ay._id, school._id);
        if (!items.length) continue;

        for (const rule of fineRules) {
            const { total, details } = calcFine(items, rule, today);
            if (total <= 0) continue;

            // Idempotency: skip if fine already logged today for this rule
            const existingToday = await FeeLedger.findOne({
                school: school._id, student: student._id, academicYear: ay._id,
                category: 'fine', referenceId: rule._id,
                createdAt: { $gte: new Date(todayKey), $lt: new Date(today.getTime() + 86400000) },
            });
            if (existingToday) continue;

            const prevEntry = await FeeLedger.findOne(
                { school: school._id, student: student._id, academicYear: ay._id },
                { runningBalance: 1 }, { sort: { createdAt: -1 } }
            );
            const running = ((prevEntry?.runningBalance || 0) + total);

            await FeeLedger.create({
                school: school._id, student: student._id, academicYear: ay._id,
                entryType: 'debit', category: 'fine', amount: total,
                description: `Late fine — ${rule.name} (${details.map(d => `${d.daysLate} days`).join(', ')})`,
                referenceType: 'FineRule', referenceId: rule._id,
                runningBalance: Math.round(running * 100) / 100,
                createdBy: null,
            });
            fineCount++;
        }
    }
    console.log(`  [${school.name}] Fine entries created: ${fineCount}`);
}

async function main() {
    console.log('[feeCron] Starting late-fee calculation —', new Date().toISOString());
    await mongoose.connect(DB_URI);

    const schools = await School.find({ isActive: true, 'modules.fees': true });
    console.log(`[feeCron] Processing ${schools.length} school(s)…`);

    for (const school of schools) {
        try {
            console.log(`  Processing: ${school.name}`);
            await runForSchool(school);
        } catch (err) {
            console.error(`  Error for school ${school.name}:`, err.message);
        }
    }

    await mongoose.disconnect();
    console.log('[feeCron] Done.');
}

main().catch(err => { console.error('[feeCron] Fatal:', err); process.exit(1); });
